[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fourfours"
authors = [{name = "M. F. Máduar", email = "maduar@lvivaldi.net"}]
dynamic = ["version", "description"]
