# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'maininterface_with_toolbarVoImfC.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import mdi_rc

class Ui_MainInterfaceClass(object):
    def setupUi(self, MainInterfaceClass):
        if not MainInterfaceClass.objectName():
            MainInterfaceClass.setObjectName(u"MainInterfaceClass")
        MainInterfaceClass.resize(793, 679)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainInterfaceClass.sizePolicy().hasHeightForWidth())
        MainInterfaceClass.setSizePolicy(sizePolicy)
        self.actionNew = QAction(MainInterfaceClass)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile(u":/images/new.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionCut = QAction(MainInterfaceClass)
        self.actionCut.setObjectName(u"actionCut")
        icon1 = QIcon()
        icon1.addFile(u":/images/cut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon1)
        self.actionClose = QAction(MainInterfaceClass)
        self.actionClose.setObjectName(u"actionClose")
        self.actionLanguage = QAction(MainInterfaceClass)
        self.actionLanguage.setObjectName(u"actionLanguage")
        self.actionOpen = QAction(MainInterfaceClass)
        self.actionOpen.setObjectName(u"actionOpen")
        icon2 = QIcon()
        icon2.addFile(u":/images/open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.action_Save = QAction(MainInterfaceClass)
        self.action_Save.setObjectName(u"action_Save")
        icon3 = QIcon()
        icon3.addFile(u":/images/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Save.setIcon(icon3)
        self.actionSave_as = QAction(MainInterfaceClass)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.action_Exit = QAction(MainInterfaceClass)
        self.action_Exit.setObjectName(u"action_Exit")
        self.action_Copy = QAction(MainInterfaceClass)
        self.action_Copy.setObjectName(u"action_Copy")
        icon4 = QIcon()
        icon4.addFile(u":/images/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Copy.setIcon(icon4)
        self.action_Paste = QAction(MainInterfaceClass)
        self.action_Paste.setObjectName(u"action_Paste")
        icon5 = QIcon()
        icon5.addFile(u":/images/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Paste.setIcon(icon5)
        self.actionAnaly_ze = QAction(MainInterfaceClass)
        self.actionAnaly_ze.setObjectName(u"actionAnaly_ze")
        self.actionApply_Energy_Calibration = QAction(MainInterfaceClass)
        self.actionApply_Energy_Calibration.setObjectName(u"actionApply_Energy_Calibration")
        self.actionClose_All = QAction(MainInterfaceClass)
        self.actionClose_All.setObjectName(u"actionClose_All")
        self.actionTile = QAction(MainInterfaceClass)
        self.actionTile.setObjectName(u"actionTile")
        self.actionCascade = QAction(MainInterfaceClass)
        self.actionCascade.setObjectName(u"actionCascade")
        self.actionNext = QAction(MainInterfaceClass)
        self.actionNext.setObjectName(u"actionNext")
        self.actionPrevious = QAction(MainInterfaceClass)
        self.actionPrevious.setObjectName(u"actionPrevious")
        self.action_File_locations = QAction(MainInterfaceClass)
        self.action_File_locations.setObjectName(u"action_File_locations")
        self.action_about = QAction(MainInterfaceClass)
        self.action_about.setObjectName(u"action_about")
        self.actionGet_InterWinner_results = QAction(MainInterfaceClass)
        self.actionGet_InterWinner_results.setObjectName(u"actionGet_InterWinner_results")
        self.actionGet_OpenGamma_results = QAction(MainInterfaceClass)
        self.actionGet_OpenGamma_results.setObjectName(u"actionGet_OpenGamma_results")
        self.actionSI_049_2009 = QAction(MainInterfaceClass)
        self.actionSI_049_2009.setObjectName(u"actionSI_049_2009")
        self.actionSet_F100D3P = QAction(MainInterfaceClass)
        self.actionSet_F100D3P.setObjectName(u"actionSet_F100D3P")
        self.actionSet_XTRA_F100 = QAction(MainInterfaceClass)
        self.actionSet_XTRA_F100.setObjectName(u"actionSet_XTRA_F100")
        self.actionSave_Plot = QAction(MainInterfaceClass)
        self.actionSave_Plot.setObjectName(u"actionSave_Plot")
        self.actionNumber_format = QAction(MainInterfaceClass)
        self.actionNumber_format.setObjectName(u"actionNumber_format")
        self.centralwidget = QWidget(MainInterfaceClass)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        MainInterfaceClass.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainInterfaceClass)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 793, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuAnalysis = QMenu(self.menubar)
        self.menuAnalysis.setObjectName(u"menuAnalysis")
        MainInterfaceClass.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainInterfaceClass)
        self.statusbar.setObjectName(u"statusbar")
        MainInterfaceClass.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainInterfaceClass)
        self.toolBar.setObjectName(u"toolBar")
        MainInterfaceClass.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSave_Plot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menuWindow.addAction(self.actionClose)
        self.menuWindow.addAction(self.actionClose_All)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionTile)
        self.menuWindow.addAction(self.actionCascade)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionNext)
        self.menuWindow.addAction(self.actionPrevious)
        self.menuHelp.addAction(self.actionLanguage)
        self.menuHelp.addAction(self.action_File_locations)
        self.menuHelp.addAction(self.actionNumber_format)
        self.menu_Help.addAction(self.action_about)
        self.menuAnalysis.addAction(self.actionAnaly_ze)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionSet_F100D3P)
        self.menuAnalysis.addAction(self.actionSet_XTRA_F100)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addSeparator()

        self.retranslateUi(MainInterfaceClass)

        QMetaObject.connectSlotsByName(MainInterfaceClass)
    # setupUi

    def retranslateUi(self, MainInterfaceClass):
        MainInterfaceClass.setWindowTitle(QCoreApplication.translate("MainInterfaceClass", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainInterfaceClass", u"&New", None))
        self.actionCut.setText(QCoreApplication.translate("MainInterfaceClass", u"Cu&t", None))
        self.actionClose.setText(QCoreApplication.translate("MainInterfaceClass", u"Close", None))
        self.actionLanguage.setText(QCoreApplication.translate("MainInterfaceClass", u"&Language", None))
        self.actionOpen.setText(QCoreApplication.translate("MainInterfaceClass", u"&Open...", None))
        self.action_Save.setText(QCoreApplication.translate("MainInterfaceClass", u"&Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainInterfaceClass", u"Save &As...", None))
        self.action_Exit.setText(QCoreApplication.translate("MainInterfaceClass", u"E&xit", None))
        self.action_Copy.setText(QCoreApplication.translate("MainInterfaceClass", u"&Copy", None))
        self.action_Paste.setText(QCoreApplication.translate("MainInterfaceClass", u"&Paste", None))
        self.actionAnaly_ze.setText(QCoreApplication.translate("MainInterfaceClass", u"Analy&ze", None))
        self.actionApply_Energy_Calibration.setText(QCoreApplication.translate("MainInterfaceClass", u"Apply &Energy Calibration", None))
        self.actionClose_All.setText(QCoreApplication.translate("MainInterfaceClass", u"Close All", None))
        self.actionTile.setText(QCoreApplication.translate("MainInterfaceClass", u"Tile", None))
        self.actionCascade.setText(QCoreApplication.translate("MainInterfaceClass", u"Cascade", None))
        self.actionNext.setText(QCoreApplication.translate("MainInterfaceClass", u"Next", None))
        self.actionPrevious.setText(QCoreApplication.translate("MainInterfaceClass", u"Previous", None))
        self.action_File_locations.setText(QCoreApplication.translate("MainInterfaceClass", u"&File locations", None))
        self.action_about.setText(QCoreApplication.translate("MainInterfaceClass", u"&about", None))
        self.actionGet_InterWinner_results.setText(QCoreApplication.translate("MainInterfaceClass", u"Get InterWinner results", None))
        self.actionGet_OpenGamma_results.setText(QCoreApplication.translate("MainInterfaceClass", u"Get OpenGamma results", None))
        self.actionSI_049_2009.setText(QCoreApplication.translate("MainInterfaceClass", u"SI-049/2009", None))
        self.actionSet_F100D3P.setText(QCoreApplication.translate("MainInterfaceClass", u"set F100D3P", None))
        self.actionSet_XTRA_F100.setText(QCoreApplication.translate("MainInterfaceClass", u"set XTRA_F100", None))
        self.actionSave_Plot.setText(QCoreApplication.translate("MainInterfaceClass", u"Save &Plot", None))
        self.actionNumber_format.setText(QCoreApplication.translate("MainInterfaceClass", u"Number format", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainInterfaceClass", u"&File", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainInterfaceClass", u"&Window", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainInterfaceClass", u"&Settings", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MainInterfaceClass", u"&Help", None))
        self.menuAnalysis.setTitle(QCoreApplication.translate("MainInterfaceClass", u"Analysis", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainInterfaceClass", u"toolBar", None))
    # retranslateUi

